tasks:
  - before: npm install -g npm@8.12.1
  - init: npm install
    command: |
     export HMR_HOST=`gp url 3000` && 
     npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true